# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###


# @name create-transcription
POST http://localhost:3333/videos/e698dabc-6e4a-4c3d-9440-64200e4bb410/transcription
Content-Type: application/json

{
  "prompt": "clean architecture, ddd"
}
###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "e698dabc-6e4a-4c3d-9440-64200e4bb410",
  "temperature": 0.7, 
  "template": "Gere um resumo sucinto da trancrição do vídeo: '''{transcription}}'''"
}

###